# Họ và Tên: Trần Tất Nguyên
# MSSV : 31251020719


## Xây dựng mô hình Logistic Regression và K-Nearest Neighbors (KNN) trên tập Dry Bean Dataset

## 1. Import thư viện

In [1]:
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier


from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

pd.set_option("display.max_columns", None)

## 2. Đọc dữ liệu

In [2]:
from pathlib import Path
import pandas as pd

DATA_DIR = Path("Dry_Bean_Dataset")

TRAIN_PATH = DATA_DIR / "dry_bean_train.csv"
TEST_PATH = DATA_DIR / "dry_bean_test.csv"

print("Train:", TRAIN_PATH.resolve())
print("Test :", TEST_PATH.resolve())

if not TRAIN_PATH.exists():
    raise FileNotFoundError(f"Không tìm thấy file tại: {TRAIN_PATH.resolve()}")

if not TEST_PATH.exists():
    raise FileNotFoundError(f"Không tìm thấy file tại: {TEST_PATH.resolve()}")

train_df = pd.read_csv(TRAIN_PATH)
test_df = pd.read_csv(TEST_PATH)

print("\nKích thước tập Train:", train_df.shape)
print("Kích thước tập Test :", test_df.shape)

display(train_df.head())

Train: /Users/nguyentran0703/mliot-pyml-2026-hw/week04/Homework_b7/Dry_Bean_Dataset/dry_bean_train.csv
Test : /Users/nguyentran0703/mliot-pyml-2026-hw/week04/Homework_b7/Dry_Bean_Dataset/dry_bean_test.csv

Kích thước tập Train: (10834, 17)
Kích thước tập Test : (2709, 17)

,area,perimeter,majoraxislength,minoraxislength,aspectration,eccentricity,convexarea,equivdiameter,extent,solidity,roundness,compactness,shapefactor1,shapefactor2,shapefactor3,shapefactor4,class
0,69471,1069.638,399.100245,225.005782,1.773733,0.825923,71088,297.410868,0.707386,0.977254,0.763027,0.745203,0.005745,0.001093,0.555328,0.985004,CALI
1,82877,1162.581,391.817013,270.836144,1.446694,0.722634,84171,324.841921,0.825986,0.984627,0.770544,0.829065,0.004728,0.001378,0.687349,0.994384,BARBUNYA
2,65042,1023.506,419.202858,198.962774,2.106941,0.880190,65748,287.774298,0.783403,0.989262,0.780231,0.686480,0.006445,0.000883,0.471255,0.992906,HOROZ
3,41315,758.920,287.438268,183.447580,1.566869,0.769858,41704,229.355383,0.791930,0.990672,0.901417,0.797929,0.006957,0.001740,0.636691,0.997611,SIRA
4,91088,1168.645,459.300729,253.950486,1.808623,0.833243,91799,340.553731,0.789051,0.992255,0.838119,0.741461,0.005042,0.000940,0.549765,0.994318,CALI

## 3. Tách feature và target

In [3]:
X_train = train_df.drop(columns="class")
y_train = train_df["class"]

X_test = test_df.drop(columns="class")
y_test = test_df["class"]

print(y_train.unique())

['CALI' 'BARBUNYA' 'HOROZ' 'SIRA' 'DERMASON' 'SEKER' 'BOMBAY']

## 4. Logistic Regression

In [4]:
logistic_model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(max_iter=1000, random_state=42))
])

logistic_model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier',
                 LogisticRegression(max_iter=1000, random_state=42))])

## 5. Đánh giá Logistic Regression

In [11]:
y_pred_lr = logistic_model.predict(X_test)

accuracy_lr = accuracy_score(y_test, y_pred_lr)
precision_lr = precision_score(y_test, y_pred_lr, average="weighted")
recall_lr = recall_score(y_test, y_pred_lr, average="weighted")
f1_score_lr = f1_score(y_test, y_pred_lr, average="weighted")

lr_metrics = pd.DataFrame({
    "Accuracy": [accuracy_lr],
    "Precision": [precision_lr],
    "Recall": [recall_lr],
    "F1 score" : [f1_score_lr]},
    index = ["Logistic Regression"]
                           )

display(lr_metrics)
print("Confusion Matrix".center(30,'-'))
print(confusion_matrix(y_test, y_pred_lr))

                     Accuracy  Precision    Recall  F1 score
Logistic Regression  0.919158   0.919726  0.919158   0.91929

-------Confusion Matrix-------
[[236   0  18   0   0   4   7]
 [  0 104   0   0   0   0   0]
 [  8   0 307   0   5   2   4]
 [  0   0   0 643   0  13  53]
 [  1   0  11   5 351   0   4]
 [  9   0   0   5   0 383   9]
 [  1   0   1  41   8  10 466]]

## 6. K-Nearest Neighbors (KNN)

In [6]:
knn_model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", KNeighborsClassifier(n_neighbors=5))
])

knn_model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('classifier', KNeighborsClassifier())])

## 7. Đánh giá KNN

In [10]:
y_pred_knn = knn_model.predict(X_test)

accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn, average="weighted")
recall_knn = recall_score(y_test, y_pred_knn, average="weighted")
f1_score_knn = f1_score(y_test, y_pred_knn, average="weighted")

knn_metrics = pd.DataFrame({
    "Accuracy": [accuracy_knn],
    "Precision": [precision_knn],
    "Recall": [recall_knn],
    "F1 score" : [f1_score_knn]},
    index = ["KNN (k=5)"]
                           )

display(knn_metrics)
print("Confusion Matrix".center(30,'-'))
print(confusion_matrix(y_test, y_pred_knn))

           Accuracy  Precision    Recall  F1 score
KNN (k=5)  0.915467   0.916315  0.915467  0.915652

-------Confusion Matrix-------
[[232   0  21   0   1   3   8]
 [  0 104   0   0   0   0   0]
 [  8   0 309   0   5   2   2]
 [  0   0   0 647   0  10  52]
 [  0   0  13   4 347   0   8]
 [  6   0   1   7   0 380  12]
 [  3   0   0  49   8   6 461]]

# 8. So sánh mô hình Logistic Regresssion và K-Nearest Neighbors

In [8]:
result = pd.DataFrame({
    "Model": ["Logistic Regression", "KNN (k=5)"],
    "Accuracy": [accuracy_lr, accuracy_knn],
    "Precision": [precision_lr, precision_knn],
    "Recall": [recall_lr, recall_knn],
    "F1 score" : [f1_score_lr, f1_score_knn]
})
display(result)

                 Model  Accuracy  Precision    Recall  F1 score
0  Logistic Regression  0.919158   0.919726  0.919158  0.919290
1            KNN (k=5)  0.915467   0.916315  0.915467  0.915652

## Nhận xét

- Cả Logistic Regression và KNN đều đạt trên 91% ở cả 4 metrics là `accuracy`, `precision`, `recall` và `f1 score`
- Logistic Regression cho `accuracy` 91.92%, cao hơn KNN (91.55%).
- Precision, Recall và F1-score của Logistic Regression cũng đều cao hơn KNN.
Do đó Logistic Regression là mô hình phù hợp hơn cho bộ dữ liệu Dry Bean trong thí nghiệm này